<?php
require_once __DIR__ . '/../../src/libs/ValidUtil.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 15:12:08.
 */
class ValidUtilTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ValidUtil
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidUtil;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ValidUtil::validISBN
     * @todo   Implement testValidISBN().
     */
    public function testValidISBN() {
        $this->assertTrue(
                 $this->object->validISBN("9784063620597")
        );
    }

}
