<?php
require_once __DIR__ . '/../../src/libs/ValidUtil.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 15:12:08.
 */
class ValidUtilTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ValidUtil
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidUtil;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * 正常なISBNコード
     * @covers ValidUtil::validISBN
     * @todo   Implement testValidISBN()
     */
    public function testValidISBN() {
        $this->assertTrue(
                 $this->object->validISBN("9784063620597")
        );
    }
    public function testValidISBN_ERROR_TOO_SHORT(){
        $this->assertEquals(
                "ISBN too short. length : 3" , $this->object->validISBN("978")
        );
    }
    public function testValidISBN_ERROR_TOO_LONG(){
        $this->assertEquals(
                "ISBN too long. length : 14" , $this->object->validISBN("97840636205971")
        );
    }
    public function testValidISBN_ERROR_NOT_VALID(){
        $this->assertEquals(
                "Input checksum digit incorrect: ISBN not valid" , $this->object->validISBN("9784063620590")
        );
    }
}
