<?php

require_once __DIR__ . '/../src/Calculator.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-19 at 12:50:26.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (0, 1) == 1.
     *
     * @covers Calculator::add
     */
    public function testAdd() {
        $this->assertEquals(
                1, $this->object->add(0, 1)
        );
    }

    /**
     * Generated from @assert (1, 2) == 4.
     *
     * @covers Calculator::add
     */
    public function testAdd2() {
        $this->assertEquals(
                3, $this->object->add(1, 2)
        );
    }

}
